#!/usr/bin/env bash
# Copy the canonical Typst program, font manifest, fonts, and crate version
# into this package before packing. The repository keeps no duplicates:
# `typst/`, `fonts/`, and `Cargo.toml` at the ctypst root stay canonical.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ROOT="$(cd "$HERE/../../.." && pwd)"

mkdir -p "$HERE/assets" "$HERE/fonts" "$HERE/src/generated"

cp "$ROOT/typst/measure-v1.typ" "$HERE/assets/measure-v1.typ"
cp "$ROOT/fonts/manifest.json" "$HERE/assets/manifest.json"
cp "$ROOT"/fonts/*.ttf "$HERE/fonts/"

VERSION="$(grep -m1 '^version' "$ROOT/Cargo.toml" | sed 's/.*"\(.*\)"/\1/')"

python3 - "$HERE" "$VERSION" <<'EOF'
import json
import sys

here, version = sys.argv[1], sys.argv[2]
typ = open(f"{here}/assets/measure-v1.typ", encoding="utf-8").read()
manifest_text = open(f"{here}/assets/manifest.json", encoding="utf-8").read()
manifest = json.loads(manifest_text)
files = [entry["file"] for entry in manifest["fonts"]]
out = (
    "// GENERATED by scripts/sync-assets.sh — do not edit.\n"
    f"export const PACKAGE_VERSION = {json.dumps(version)};\n"
    f"export const MEASURE_V1_TYP = {json.dumps(typ)};\n"
    f"export const MANIFEST_JSON = {json.dumps(manifest_text)};\n"
    f"export const MANIFEST = {json.dumps(manifest)};\n"
    f"export const FONT_FILES = {json.dumps(files)};\n"
)
open(f"{here}/src/generated/measure-asset.ts", "w", encoding="utf-8").write(out)
print(f"synced measure-v1.typ, manifest.json, {len(files)} fonts, version {version}")
EOF
